config/routes.rb
Rails.application.routes.draw do
  get 'search/index' => 'search#index', as: 'search'
  root 'home#top'
  get 'home/about' => 'home#about'

  get 'users/mail' => 'users#mail', as: 'mail'
  get 'rooms/users/:id' => "rooms#dm_create", as: 'dm_create'
  get 'rooms/:id' => 'rooms#show', as: 'room'

  devise_for :users

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show, :edit, :update]

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  get 'users/:id/following' => 'users#following', as: 'following'
  get 'users/:id/follow' => 'users#followers', as: 'followers'

  get 'users/:id/welcome' => 'users#welcome'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得

  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  has_many :user_rooms
  has_many :users, through: :user_rooms
  has_many :posts

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  validates :name,length: { in: 2..20 }
  validates :introduction, length: { maximum: 50}

  attachment :profile_image

  include JpPrefecture
  jp_prefecture :prefecture_code
  
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # ログイン済みユーザーのみアクセス許可
  before_action :authenticate_user!

  before_action :current_user_check, only: [:edit, :update]

  def mail
    unless current_user.mail_check
      UserMailer.welcome_email(current_user).deliver_now
    end
    redirect_to user_path(current_user)
  end

  def welcome
    @user = User.find(params[:id])
    @user.mail_check = true
    @user.save
  end

  def index
    @users = User.all
    @book_new = Book.new
    # render :index
    # renderメソッドはユーザーへのレスポンスとして送信すべき内容を指定している。(http://localhost:3000/usersというリクエストに対してbooks/index.html.erbを返している)
    # railsはレスポンスとして送信すべき内容を指定していない場合、アクション名と同じ名前のviewを返す。なのでrender :indexとかく必要はない。render :indexが省略されているとも言える。
    # 他のアクションでも同じ。
  end

  def show
    @user = User.find(params[:id])
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'successfully updated.'
    else
      render :edit
    end
  end

  def following
    @title = "フォロー"
    @user = User.find(params[:id])
    @book = Book.new
    @users = @user.following_user.all
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user = User.find(params[:id])
    @book = Book.new
    @users = @user.follower_user.all
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :postcode, :prefecture_name, :address_city, :address_street, :address_building)
  end

  def current_user_check
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'books/errors', var: @user %>

<div class="col-md-6 col-md-offset-3">
  <h1>User info</h1>
  <%= form_for(@user) do |f| %>
    <div class="field row">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, class: "col-xs-12" %>
    </div>

    <div class="field row">
      <%= f.label :profile_image, "Image" %>
      <%= f.attachment_field :profile_image, class: "col-xs-12" %>
    </div>
    <div class="field row">
      <%= f.label :introduction %>
      <%= f.text_area :introduction, autofocus: true, class: "col-xs-12" %>
    </div>
    <br>
    <div class="actions row">
      <p><%= f.submit class: "btn btn-primary col-xs-12" %></p>
    </div>
    
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render 'books/list', user: current_user, book: @book_new %>
    </div>

    <div class="col-md-9">

      <h2>Books</h2>
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%=  attachment_image_tag user, :profile_image, format:"jpeg",fallback:"no_image.jpg", size:"40x40" %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to 'Show', user_path(user) %>
              </td>
            

              <td>
                <%= link_to follow_path(user) do %>
                    <%= user.following_user.count %>フォロー
                <% end %>
              
                <%= link_to unfollow_path(user) do %>
                  <%= user.follower_user.count %>フォロワー
                <% end %>
              </td>
        
              <td>
                <% if user == current_user %>
                <% elsif current_user.following?(user) %>
                  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: "btn btn-large btn-primary", remote: true %>
                <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "btn btn-large btn-primary", remote: true %>
                <% end %>
              </td>
            </tr>
          <% end %>
          
        </tbody>

      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', user: @user, book: @book_new %>
    </div>
    
    <div class="col-md-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @user.books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%=  attachment_image_tag book.user, :profile_image, format:"jpeg",fallback:"no_image.jpg", size:"40x40" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>

  </div>
</div>

app/views/users/show_follow.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'books/list', user: @user, book: @book %>
    </div>
    <div class="col-xs-9">

      <h2><%= @title %></h2>
      <table class="table table-hover table-inverse">


        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
        <% @users.each do |user| %>

          <tr>
            <td>
              <%=  attachment_image_tag user, :profile_image, format:"jpeg",fallback:"no_image.jpg", size:"40x40" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to 'Show', user_path(user) %>
            </td>
          </tr>
        </tbody>

        <% end %>

      </table>
    </div>

  </div>
</div>

app/views/users/welcome.html.erb
<h3>ようこそBookersへ</h3>
<%= link_to "こちらをクリックしてください", user_path(@user) %>