config/routes.rb
Rails.application.routes.draw do
  get 'search/index' => 'search#index', as: 'search'
  root 'home#top'
  get 'home/about' => 'home#about'

  get 'users/mail' => 'users#mail', as: 'mail'
  get 'rooms/users/:id' => "rooms#dm_create", as: 'dm_create'
  get 'rooms/:id' => 'rooms#show', as: 'room'

  devise_for :users

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show, :edit, :update]

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  get 'users/:id/following' => 'users#following', as: 'following'
  get 'users/:id/follow' => 'users#followers', as: 'followers'

  get 'users/:id/welcome' => 'users#welcome'
end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   has_many :favorites, dependent: :destroy
   has_many :comments, dependent: :destroy
 
   validates :title, length: { minimum: 1 }
   validates :body, length: { in: 1..200 }

   def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
   end

 end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :current_user_check, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
    @book_new = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @comment = Comment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end


  def edit
    @book = Book.find(params[:id])
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_path, notice: 'Book was successfully destroyed.'
    else
      redirect_to book_path(@book), notice: 'error destroyed.'
    end
  end

  private


  def book_params
    params.require(:book).permit(:title, :body)
  end

  def current_user_check
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<td>
  <%= link_to user_path(comment.user) do %>
    <%=  attachment_image_tag comment.user, :profile_image, format:"jpeg",fallback:"no_image.jpg", size:"25x25" %><br>
    <%= comment.user.name %>
  <% end %>
</td>
<td><%= comment.comment %></td>
<% if comment.user == current_user %>
  <td><%= link_to "Destroy", book_comments_path(comment), method: :delete, remote: true %></td>
  <td><%= comment.id %></td>
<% end %>

app/views/books/_errors.html.erb
<% if var.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h4><%= var.errors.count %>件のエラーが発生しました。</h4>
    <ul>
       <% var.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
 <% end %>

app/views/books/_list.html.erb
<%= flash[:notice] %>

<div>
  <h2>User Info</h2>
</div>

<%= attachment_image_tag user, :profile_image, :fill, 1800, 1800, format: 'jpeg', size:'100x100', fallback: "no_image.jpg" %>

<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<table class="table">
  <tbody>
    <tr>
      <th>
        <%= link_to following_path(user) do %>
            <%= user.following_user.count %>フォロー
        <% end %>
      </th>
      <th>
        <%= link_to followers_path(user) do %>
          <%= user.follower_user.count %>フォロワー
        <% end %>
      </th>
    </tr>
  </tbody>
</table>

<table class="table">
  <tbody>
    <tr>
      <th>
        <% if user == current_user %>
        <% elsif current_user.following?(user) %>
          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST, class: "btn btn-large btn-primary", remote: true %>
        <% else %>
          <%= link_to 'フォローする', follow_path(user.id), method: :POST, class: "btn btn-large btn-primary", remote: true %>
        <% end %>
      </th>
    </tr>
  </tbody>
</table>

<div class = "row">
  <% if user == current_user %>
  <% else %>
    <%= link_to 'DMを送る', dm_create_path(user.id), class: "col-xs-12 btn btn-large btn-primary" %>
  <% end %>
</div>

<div class = "row">
  <%= link_to "", edit_user_path(user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench"  %>
</div>

<h2>New book</h2>

<%= form_for(book) do |f| %>
  <div class="field row">
    <h4>Title</h4>
    <%= f.text_field :title, class:"col-xs-12" %>
  </div>

  <div class="field row">
    <h4>Opinion</h4>
    <%= f.text_area :body, class:"col-xs-12"%>
  </div>

  <div class="actions row">
    <!--<%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %> としなくてもrailsが自動で"Create Bookをいう文字を生成してくれる"-->
    <br><%= f.submit class:"btn btn-primary col-xs-12" %>
  </div>
<% end %>

app/views/books/_post.html.erb
<td>
  <%= link_to user_path(book.user) do %>
    <%=  attachment_image_tag book.user, :profile_image, format:"jpeg",fallback:"no_image.jpg", size:"40x40" %><br>
    <%= book.user.name %>
  <% end %>
</td>
<td><%= link_to book.title, book_path(book) %></td>
<td><%= book.body %></td>

<% if book.favorited_by?(current_user) %>
  <td>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      <%= book.favorites.count %>いいね
    <% end %>
  </td>
<% else %>
  <td>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <i class="fa fa-heart-o" aria-hidden="true"></i>
      <%= book.favorites.count %>いいね
    <% end %>
  </td>

<% end %>

<td>
    <i class="fa fa-comment"></i>
    <%= book.comments.count %>
</td>

app/views/books/edit.html.erb
<%= render 'books/errors', var: @book %>

<div class="col-md-6 col-md-offset-3">
  <h1>Editing Book</h1>

  <%= form_for(@book) do |f| %>
    <div class="field row">
      <h4>Title</h4>
      <%= f.text_field :title, class:"col-xs-12" %>
    </div>

    <div class="field row">
      <h4>Body</h4>
      <%= f.text_area :body, class:"col-xs-12" %>
    </div>
    <br>
    <div class="actions row">
      <p><%= f.submit class: "btn btn-primary col-xs-12" %></p>
    </div>
    <% end %>

  <br>
  <p>
    <%= link_to "Show", book_path(@book) %>
    |
    <%= link_to "Back", books_path %>
  </p>
</div>

app/views/books/index.html.erb
<%= render 'books/errors', var: @book_new %>

<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render 'books/list', user: current_user, book: @book_new %>
    </div>

    <div class="col-md-9">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr class="book_<%= book.id %>">
              <%= render 'post', book: book %>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/books/show.html.erb
<%= render 'books/errors', var: @book_new %>

<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render 'books/list', user: @book.user, book: @book_new %>
    </div>

    <div class="col-md-9">

      <h2>Books</h2>
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <tr class="book_<%= @book.id %>">
            <%= render 'post', book: @book %>
          </tr>
        </tbody>

      </table>

      <div class="col-xs-9">
        <h4>Comment</h4>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
              <% if @book.user != current_user %>
                <%= form_for [@book, @comment], url: book_comments_path(@book), method: :post, remote: true do |f| %>
                  <%= f.text_area :comment, rows:'2', class: "form-control",placeholder: "コメントをここに" %>
                  <%= f.submit "送信する", id:"come"%>
                <% end %>
              <% end %>

              <% @book.comments.each do |comment| %>
                <tr class="comment_<%= comment.id %>">
                  <%= render 'comment', comment: comment %>
                </tr>
              <% end %>
              <%# trタグがもとからないとレイアウトが崩れる,spanだとtabeleタグの外に出てしまう %>
              <%# beforeで#come_newの上にどんどんtrタグが追加される %>
              <tr id="come_new"></tr>

          </tbody>
        </table>
      </span>

    </div>

  </div>
</div>